globalArguments:
  - "--global.sendanonymoususage=false"
  - "--global.checknewversion=false"

additionalArguments:
#  - "--serversTransport.insecureSkipVerify=true"
  - "--log.level=INFO"
  - "--entryPoints.web.proxyProtocol.trustedIPs=10.0.0.200"
  - "--entryPoints.websecure.proxyProtocol.trustedIPs=10.0.0.200"

deployment:
  enabled: true
  replicas: 3
  annotations: {}
  podAnnotations: {}
  additionalContainers: []
  initContainers: []

ports:
  web:
    redirectTo: websecure
  websecure:
    tls:
      enabled: true

ingressRoute:
  dashboard:
    enabled: false

providers:
  kubernetesCRD:
    enabled: true
    ingressClass: traefik-external
  kubernetesIngress:
    enabled: true
    publishedService:
      enabled: false

rbac:
  enabled: true

service:
  enabled: true
  type: LoadBalancer
  annotations: {
    load-balancer.hetzner.cloud/name: "k8s-agent",
    load-balancer.hetzner.cloud/use-private-ip: true
  }
  labels: {}
  loadBalancerSourceRanges: []
  externalIPs: []