#cloud-config
runcmd:
  - apt update
  - apt upgrade -y
  - apt install apparmor apparmor-utils git -y
  - timedatectl set-timezone Europe/Berlin
# - export HCLOUD_TOKEN=HETZNER_TOKEN_HERE
# - wget https://github.com/hetznercloud/cli/releases/download/v1.30.3/hcloud-linux-amd64.tar.gz
# - tar -zxvf hcloud-linux-amd64.tar.gz
# - ./hcloud server add-to-placement-group --placement-group k8s-agent-LOCATION $(hostname -f)
# - printf '#!/bin/bash\nIPADDR_1=1\nwhile true\ndo\n    ERROR=$(./hcloud server attach-to-network --network k8s --ip 10.2.0.$IPADDR_1 $(hostname -f) 2>&1)\n    echo $ERROR\n    case $ERROR in\n        *"server_already_attached"*)\n            echo already attached\n            break;\n            ;;\n        *"ip_not_available"*)\n            echo ip used\n            IPADDR_1=$(( $IPADDR_1 + 1 ))\n            ;;\n        *)\n            echo ip found and server attached\n            break\n            ;;\n    esac\ndone' > setup_ip.sh
# - [ bash, setup_ip.sh ]
# - sleep 30
  - curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION="v1.25.0-rc1+k3s1" INSTALL_K3S_EXEC="agent --server https://10.0.0.100:6443 --token K3S_TOKEN_HERE --node-name="$(hostname -f)" --kubelet-arg="cloud-provider=external" --node-ip=$(ip -f inet addr show ens10 | sed -En -e 's/.*inet ([0-9.]+).*/\1/p') --node-external-ip=$(hostname -I | awk '{print $1}') --flannel-iface=ens10" sh -
